// <auto-generated />
namespace LesoftWuye2.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V_13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V_13));
        
        string IMigrationMetadata.Id
        {
            get { return "201706041438200_V_13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
